version: "3.7"

services:
  # ==========================================
  # Chatwoot-Go Application
  # ==========================================
  app:
    image: oyaga/chatwoot-go:latest
    container_name: chatwoot-go-app
    restart: unless-stopped
    networks:
      - AikaNet
    environment:
      # Conexão DB: Apontando para o NOME DO SERVIÇO 'chatwoot-db'
      - DATABASE_URL=host=chatwoot-db user=chatwoot password=chatwoot123 dbname=chatwoot_go port=5432 sslmode=disable TimeZone=America/Sao_Paulo

      # Conexão Redis: Apontando para o NOME DO SERVIÇO 'chatwoot-cache'
      - REDIS_URL=redis://chatwoot-cache:6379

      # Conexão MinIO: Tentando conectar no serviço 'minio' da rede AikaNet
      # Se falhar, verifique se o nome do serviço na stack antiga é 'minio'
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=AikaDesign
      - MINIO_SECRET_KEY=@AikaNakamura_Minio_329263
      - MINIO_USE_SSL=false

      # Buckets Customizados
      - MINIO_BUCKET_AVATARS=chatwoot-go-avatars
      - MINIO_BUCKET_ATTACHMENTS=chatwoot-go-attachments

      # Configurações Gerais
      - FRONTEND_URL=https://ct.aikanakamura.com
      - JWT_SECRET=c5f444c7b6fa1ec3b1bcfd1949c67170
      - GIN_MODE=release

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatwoot_go.rule=Host(`ct.aikanakamura.com`)"
        - "traefik.http.routers.chatwoot_go.entrypoints=websecure"
        - "traefik.http.routers.chatwoot_go.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.chatwoot_go.service=chatwoot_go"
        - "traefik.http.services.chatwoot_go.loadbalancer.server.port=8080"
        - "traefik.http.services.chatwoot_go.loadbalancer.passHostHeader=true"

    depends_on:
      - chatwoot-db
      - chatwoot-cache

  # ==========================================
  # PostgreSQL (Nome do Serviço Único)
  # ==========================================
  chatwoot-db:
    image: postgres:16-alpine
    container_name: chatwoot-go-postgres-container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=chatwoot
      - POSTGRES_PASSWORD=chatwoot123
      - POSTGRES_DB=chatwoot_go
    volumes:
      - chatwoot_go_postgres_data:/var/lib/postgresql/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # Redis (Nome do Serviço Único)
  # ==========================================
  chatwoot-cache:
    image: redis:7-alpine
    container_name: chatwoot-go-redis-container
    restart: unless-stopped
    volumes:
      - chatwoot_go_redis_data:/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # Setup Buckets
  # ==========================================
  createbuckets:
    image: minio/mc
    networks:
      - AikaNet
    entrypoint: >
      /bin/sh -c "
      echo 'Connecting to existing MinIO at minio:9000...';
      until /usr/bin/mc config host add myminio http://minio:9000 AikaDesign @AikaNakamura_Minio_329263; do echo '...waiting for minio...'; sleep 3; done;

      echo 'Creating buckets for Chatwoot-Go...';
      /usr/bin/mc mb -p myminio/chatwoot-go-avatars;
      /usr/bin/mc mb -p myminio/chatwoot-go-attachments;

      echo 'Setting public policies...';
      /usr/bin/mc anonymous set public myminio/chatwoot-go-avatars;
      /usr/bin/mc anonymous set public myminio/chatwoot-go-attachments;

      echo 'Buckets Configured Successfully';
      exit 0;
      "
    deploy:
      restart_policy:
        condition: on-failure

networks:
  AikaNet:
    external: true
    name: AikaNet

volumes:
  chatwoot_go_postgres_data:
  chatwoot_go_redis_data:
