version: "3.7"

services:
  # ==========================================
  # Chatwoot-Go Application
  # ==========================================
  app:
    image: oyaga/chatwoot-go:latest
    container_name: chatwoot-go-app
    restart: unless-stopped
    networks:
      - AikaNet
    environment:
      # Conexão DB (Interna na stack)
      - DATABASE_URL=postgres://chatwoot:chatwoot123@chatwoot-go-postgres:5432/chatwoot_go?sslmode=disable

      # Conexão Redis (Interna na stack)
      - REDIS_URL=redis://chatwoot-go-redis:6379

      # Conexão MinIO (Storage)
      - MINIO_ENDPOINT=chatwoot-go-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_USE_SSL=false

      # Configurações Gerais
      - FRONTEND_URL=https://msn.aikanakamura.com
      - JWT_SECRET=c5f444c7b6fa1ec3b1bcfd1949c67170
      - GIN_MODE=release

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"

        # Router HTTPS (msn.aikanakamura.com)
        - "traefik.http.routers.chatwoot_go.rule=Host(`msn.aikanakamura.com`)"
        - "traefik.http.routers.chatwoot_go.entrypoints=websecure"
        - "traefik.http.routers.chatwoot_go.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.chatwoot_go.service=chatwoot_go"

        # Apontamento para porta interna 8080
        - "traefik.http.services.chatwoot_go.loadbalancer.server.port=8080"
        - "traefik.http.services.chatwoot_go.loadbalancer.passHostHeader=true"

  # ==========================================
  # PostgreSQL (Dedicado para Chatwoot-Go)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: chatwoot-go-postgres
    restart: unless-stopped
    namespace: chatwoot_go # Isolamento
    environment:
      - POSTGRES_USER=chatwoot
      - POSTGRES_PASSWORD=chatwoot123
      - POSTGRES_DB=chatwoot_go
    volumes:
      - chatwoot_go_postgres_data:/var/lib/postgresql/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # Redis
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: chatwoot-go-redis
    restart: unless-stopped
    volumes:
      - chatwoot_go_redis_data:/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # MinIO (Object Storage)
  # ==========================================
  minio:
    image: minio/minio:latest
    container_name: chatwoot-go-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - chatwoot_go_minio_data:/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager
      # Nota: Para acessar arquivos publicamente, idealmente você configuraria outro subdomínio
      # ex: files.aikanakamura.com apontando para este container porta 9000
      # labels:
      #   - "traefik.enable=true"
      #   - "traefik.http.routers.chatwoot_go_minio.rule=Host(`files.aikanakamura.com`)"
      #   - "traefik.http.services.chatwoot_go_minio.loadbalancer.server.port=9000"

  # ==========================================
  # Setup Buckets (Auto-run)
  # ==========================================
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin123; do echo '...waiting for minio...'; sleep 1; done;
      /usr/bin/mc mb -p myminio/avatars;
      /usr/bin/mc mb -p myminio/attachments;
      /usr/bin/mc anonymous set public myminio/avatars;
      /usr/bin/mc anonymous set public myminio/attachments;
      echo 'MinIO Buckets Configured';
      exit 0;
      "
    networks:
      - AikaNet
    deploy:
      restart_policy:
        condition: on-failure

# ==========================================
# Network & Volumes
# ==========================================
networks:
  AikaNet:
    external: true
    name: AikaNet

volumes:
  chatwoot_go_postgres_data:
  chatwoot_go_redis_data:
  chatwoot_go_minio_data:
