version: "3.7"

services:
  # ==========================================
  # Chatwoot-Go Application
  # ==========================================
  app:
    image: oyaga/chatwoot-go:latest
    container_name: chatwoot-go-app
    restart: unless-stopped
    networks:
      - AikaNet
    environment:
      # Conexão DB (Interna nesta stack - Novo Postgres) - Formato DSN para evitar erros de parsing
      - DATABASE_URL=host=chatwoot-go-postgres user=chatwoot password=chatwoot123 dbname=chatwoot_go port=5432 sslmode=disable TimeZone=America/Sao_Paulo

      # Conexão Redis (Interna nesta stack - Novo Redis)
      - REDIS_URL=redis://chatwoot-go-redis:6379

      # Conexão MinIO (Usa o serviço 'minio' que JÁ ESTÁ RODANDO na rede AikaNet)
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=AikaDesign
      - MINIO_SECRET_KEY=@AikaNakamura_Minio_329263
      - MINIO_USE_SSL=false

      # Configurações Gerais
      - FRONTEND_URL=https://ct.aikanakamura.com
      - JWT_SECRET=c5f444c7b6fa1ec3b1bcfd1949c67170
      - GIN_MODE=release

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"

        # Router HTTPS (ct.aikanakamura.com)
        - "traefik.http.routers.chatwoot_go.rule=Host(`ct.aikanakamura.com`)"
        - "traefik.http.routers.chatwoot_go.entrypoints=websecure"
        - "traefik.http.routers.chatwoot_go.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.chatwoot_go.service=chatwoot_go"

        # Apontamento para porta interna 8080
        - "traefik.http.services.chatwoot_go.loadbalancer.server.port=8080"
        - "traefik.http.services.chatwoot_go.loadbalancer.passHostHeader=true"

    depends_on:
      - postgres
      - redis

  # ==========================================
  # PostgreSQL (Dedicado para Chatwoot-Go)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: chatwoot-go-postgres
    restart: unless-stopped
    # Namespace removido para compatibilidade
    environment:
      - POSTGRES_USER=chatwoot
      - POSTGRES_PASSWORD=chatwoot123
      - POSTGRES_DB=chatwoot_go
    volumes:
      - chatwoot_go_postgres_data:/var/lib/postgresql/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # Redis (Dedicado para Chatwoot-Go)
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: chatwoot-go-redis
    restart: unless-stopped
    volumes:
      - chatwoot_go_redis_data:/data
    networks:
      - AikaNet
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # Setup Buckets (No MinIO Existente)
  # ==========================================
  createbuckets:
    image: minio/mc
    networks:
      - AikaNet
    entrypoint: >
      /bin/sh -c "
      echo 'Connecting to existing MinIO at minio:9000...';
      until /usr/bin/mc config host add myminio http://minio:9000 AikaDesign @AikaNakamura_Minio_329263; do echo '...waiting for minio...'; sleep 3; done;

      echo 'Creating buckets for Chatwoot-Go...';
      /usr/bin/mc mb -p myminio/chatwoot-go-avatars;
      /usr/bin/mc mb -p myminio/chatwoot-go-attachments;

      echo 'Setting public policies...';
      /usr/bin/mc anonymous set public myminio/chatwoot-go-avatars;
      /usr/bin/mc anonymous set public myminio/chatwoot-go-attachments;

      echo 'Buckets Configured Successfully';
      exit 0;
      "
    deploy:
      restart_policy:
        condition: on-failure

# ==========================================
# Network & Volumes
# ==========================================
networks:
  AikaNet:
    external: true
    name: AikaNet

volumes:
  chatwoot_go_postgres_data:
  chatwoot_go_redis_data:
